url: "https://dev.sina-chan.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sina-chan"
description: >- # this means to ignore newlines until "baseurl:"
  思惟奈(Sina-chan)は、mii-10によって作成された、高機能/高性能のDiscordボットです。<br>現在、1,000サーバー以上で使われています。あなたも使ってみませんか?
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title

plugins:
  - jekyll-feed
markdown: kramdown
lang: ja-jp
