name: 表示不具合の報告（バグ報告）
description: レイアウト崩れ・リンク切れなどを報告します
title: "[バグ] "
labels: ["bug"]
assignees: mii-10, takumi0213
body:
  - type: markdown
    attributes:
      value: |
        🐞 **不具合の内容と再現手順をできるだけ詳しく記載してください。**

  - type: textarea
    id: overview
    attributes:
      label: 問題の概要
      description: どのような問題が発生しましたか？
      placeholder: 例）`about.md`でリンクが切れています
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 手順を番号付きで記載してください
      placeholder: |
        1. ページにアクセス
        2. ニュースページへ移動
        3. リンク切れ
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: 問題のあるページのパス
      placeholder: 例）/about.html

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - ''
        - 緊急
        - 高
        - 中
        - 低
        - 超低
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: スクリーンショット（任意）
      description: 可能であれば貼り付けてください
